In [1]:
# activate virtual display
from pyvirtualdisplay import Display
display = Display(visible=0, size=(1400, 900))
display.start()

<Display cmd_param=['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '1400x900x24', ':1001'] cmd=['Xvfb', '-br', '-nolisten', 'tcp', '-screen', '0', '1400x900x24', ':1001'] oserror=None return_code=None stdout="None" stderr="None" timeout_happened=False>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# This code creates a virtual display to draw game images on. 
# If you are running locally, just ignore it
import os
if type(os.environ.get("DISPLAY")) is not str or len(os.environ.get("DISPLAY"))==0:
    !bash ../xvfb start
    %env DISPLAY=:1

In [3]:
import gym

In [9]:
# https://github.com/vmayoral/basic_reinforcement_learning/blob/master/tutorial3/README.mdenv = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

[-0.03357023  0.0290899   0.04444304 -0.01046633]
[-0.03298843 -0.16664031  0.04423371  0.29590104]
[-0.03632124  0.02782404  0.05015173  0.0174903 ]
[-0.03576476 -0.16797993  0.05050154  0.3255654 ]
[-0.03912436  0.02638796  0.05701284  0.04922641]
[-0.0385966  -0.16950319  0.05799737  0.35933841]
[-0.04198666 -0.36539958  0.06518414  0.66973061]
[-0.04929465 -0.1712416   0.07857875  0.3982627 ]
[-0.05271948  0.02268277  0.08654401  0.13135214]
[-0.05226583  0.21646526  0.08917105 -0.13282153]
[-0.04793652  0.41020425  0.08651462 -0.39609384]
[-0.03973244  0.60399899  0.07859274 -0.66029517]
[-0.02765246  0.40787639  0.06538684 -0.34393688]
[-0.01949493  0.60201016  0.0585081  -0.61530522]
[-0.00745473  0.79626793  0.046202   -0.88900171]
[ 0.00847063  0.99073348  0.02842196 -1.1668102 ]
[ 0.0282853   0.79525344  0.00508576 -0.86535362]
[ 0.04419037  0.60006263 -0.01222131 -0.571076  ]
[ 0.05619162  0.79535382 -0.02364283 -0.86758387]
[ 0.0720987   0.99078936 -0.04099451 -1.16760561]


[ 0.11402948  1.76215116 -0.15397816 -2.61771562]
[ 0.1492725   1.5685107  -0.20633247 -2.37578235]
Episode finished after 17 timesteps
[ 0.02268393  0.00784664  0.04143874 -0.03027083]
[ 0.02284086  0.20235059  0.04083332 -0.30959679]
[ 0.02688787  0.39686768  0.03464138 -0.58912755]
[ 0.03482523  0.59148787  0.02285883 -0.87070016]
[ 0.04665498  0.78629156  0.00544483 -1.15610945]
[ 0.06238082  0.59109905 -0.01767736 -0.86172425]
[ 0.0742028   0.39622222 -0.03491184 -0.57465154]
[ 0.08212724  0.59181577 -0.04640487 -0.87812508]
[ 0.09396356  0.39735409 -0.06396738 -0.60038472]
[ 0.10191064  0.2031826  -0.07597507 -0.32851676]
[ 0.10597429  0.3992993  -0.08254541 -0.64415837]
[ 0.11396028  0.20541886 -0.09542857 -0.37856875]
[ 0.11806865  0.40175735 -0.10299995 -0.69974995]
[ 0.1261038   0.20820275 -0.11699495 -0.44118522]
[ 0.13026786  0.40476917 -0.12581865 -0.76833732]
[ 0.13836324  0.21158298 -0.1411854  -0.51774183]
[ 0.1425949   0.01870169 -0.15154023 -0.27266943]
[ 0.14296893  

[ 0.06112048  0.43582622 -0.06627227 -0.63432201]
[ 0.069837    0.24168824 -0.07895871 -0.36322407]
[ 0.07467077  0.04777209 -0.08622319 -0.09644585]
[ 0.07562621 -0.14601504 -0.0881521   0.16783677]
[ 0.07270591  0.05025088 -0.08479537 -0.15130216]
[ 0.07371093 -0.14356097 -0.08782141  0.1134711 ]
[ 0.07083971 -0.33732194 -0.08555199  0.37720615]
[ 0.06409327 -0.14109572 -0.07800787  0.05882171]
[ 0.06127135 -0.33501755 -0.07683143  0.3259088 ]
[ 0.054571   -0.5289663  -0.07031326  0.59340746]
[ 0.04399168 -0.72303722 -0.05844511  0.86313946]
[ 0.02953093 -0.52717035 -0.04118232  0.55266771]
[ 0.01898752 -0.72169049 -0.03012896  0.83209636]
[ 0.00455371 -0.52617004 -0.01348704  0.53009221]
[-0.00596969 -0.7210997  -0.00288519  0.81849503]
[-0.02039168 -0.91618204  0.01348471  1.11026907]
[-0.03871532 -1.11147854  0.03569009  1.40715158]
[-0.06094489 -1.30702476  0.06383312  1.71077477]
[-0.08708539 -1.1126915   0.09804862  1.43862276]
[-0.10933922 -0.91890493  0.12682107  1.17811915]
